name: CI
on: [pull_request]
jobs:
  macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: execute-script
        run: ./CI/before-script-osx.sh
        shell: sh
        working-directory: .
